version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI:  https://sqladmin.xxps.tp.edu.tw
    networks:
    - core-infra
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.phpmyadmin.loadbalancer.server.port: "80"
        traefik.http.services.phpmyadmin.loadbalancer.server.scheme: "http"
        traefik.http.routers.sqladmin_http.entrypoints: "web"
        traefik.http.routers.sqladmin_http.rule: "Host(`sqladmin.xxps.tp.edu.tw`)"
        traefik.http.routers.sqladmin_http.middlewares: "https_redirect"
        traefik.http.routers.sqladmin_https.entrypoints: "web-secure"
        traefik.http.routers.sqladmin_https.rule: "Host(`sqladmin.xxps.tp.edu.tw`)"
        traefik.http.routers.sqladmin_https.tls: "true"
        traefik.http.routers.sqladmin_https.tls.certresolver: "letsencrypt"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: db_passwd
    volumes:
    - /nas_storage/mysql:/var/lib/mysql
    networks:
    - core-infra
    ports:
    - "3306:3306"
    
  draw-io:
    image: leejoneshane/draw.io
    networks:
    - core-infra
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.drawio.loadbalancer.server.port: "80"
        traefik.http.services.drawio.loadbalancer.server.scheme: "http"
        traefik.http.routers.drawio_http.entrypoints: "web"
        traefik.http.routers.drawio_http.rule: "Host(`draw.xxps.tp.edu.tw`)"
        traefik.http.routers.drawio_http.middlewares: "https_redirect"
        traefik.http.routers.drawio_https.entrypoints: "web-secure"
        traefik.http.routers.drawio_https.rule: "Host(`draw.xxps.tp.edu.tw`)"
        traefik.http.routers.drawio_https.tls: "true"
        traefik.http.routers.drawio_https.tls.certresolver: "letsencrypt"

  office:
    cap_add:
    - MKNOD
    image: leejoneshane/collabora_tw
    environment:
      server_name: office.meps.tp.edu.tw
      domain: next.xxps.tp.edu.tw
      password: your_passwd
      username: admin
      dictionaries: en_US
    volumes:
    - /nas_storage/nextcloud_office/loolwsd.xml:/etc/loolwsd/loolwsd.xml
    networks:
    - core-infra
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.office.loadbalancer.server.port: "9980"
        traefik.http.services.office.loadbalancer.server.scheme: "http"
        traefik.http.routers.office_http.entrypoints: "web"
        traefik.http.routers.office_http.rule: "Host(`office.xxps.tp.edu.tw`)"
        traefik.http.routers.office_http.middlewares: "https_redirect"
        traefik.http.routers.office_https.entrypoints: "web-secure"
        traefik.http.routers.office_https.rule: "Host(`office.xxps.tp.edu.tw`)"
        traefik.http.routers.office_https.tls: "true"
        traefik.http.routers.office_https.tls.certresolver: "letsencrypt"

  nextcloud:
    image: leejoneshane/nextcloud
    hostname: next.xxps.tp.edu.tw
    environment:
      ORG: xxps
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: db_passwd
      MYSQL_DATABASE: nextcloud
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: your_passwd
      NEXTCLOUD_TRUSTED_DOMAINS: next.xxps.tp.edu.tw
      NEXTCLOUD_DATA_DIR: /var/www/html/data
      NEXTCLOUD_UPDATE: 1
      SMTP_HOST: smtp.gmail.com
      SMTP_SECURE: ssl
      SMTP_PORT: 465
      SMTP_NAME: webmaster@xxps.tp.edu.tw
      SMTP_PASSWORD: gmail_passwd
      MAIL_DOMAIN: xxxps.tp.edu.tw
      APACHE_DISABLE_REWRITE_IP: 1
      TRUSTED_PROXIES: 10.0.2.0/24
      PHP_MEMORY_LIMIT: -1
      PHP_UPLOAD_LIMIT: 2048M
    volumes:
    - /nas_storage/nextcloud/config:/var/www/html/config
    - /nas_storage/nextcloud/data:/var/www/html/data
    - /nas_storage/nextcloud/custom_apps:/var/www/html/custom_apps
    networks:
    - core-infra
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.nextcloud.loadbalancer.server.port: "80"
        traefik.http.services.nextcloud.loadbalancer.server.scheme: "http"
        traefik.http.routers.nextcloud_http.entrypoints: "web"
        traefik.http.routers.nextcloud_http.rule: "Host(`next.xxps.tp.edu.tw`)"
        traefik.http.routers.nextcloud_http.middlewares: "https_redirect"
        traefik.http.routers.nextcloud_https.entrypoints: "web-secure"
        traefik.http.routers.nextcloud_https.rule: "Host(`next.xxps.tp.edu.tw`)"
        traefik.http.routers.nextcloud_https.tls: "true"
        traefik.http.routers.nextcloud_https.tls.certresolver: "letsencrypt"

networks:
  core-infra:
    external: true
